package Frame.Views;

import java.awt.Component;
import static java.lang.Integer.parseInt;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Face extends javax.swing.JFrame {
 
    /**
     * Creates new form Face
     */
    public Face() {
        initComponents();
       // --setEditable(false)-- No permite al usuario editar el textbox
        jtxbMonto.setEditable(false);
         jtxbVuelto.setEditable(false);
        //Oculta los objetos al cargar el 
         jlblVuelto.setVisible(false);
        jlblShow.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxbVuelto = new javax.swing.JTextField();
        jtxbMonto = new javax.swing.JTextField();
        jbtnpepsi = new javax.swing.JButton();
        jbtnCocaCola = new javax.swing.JButton();
        jbtnPago = new javax.swing.JButton();
        jlblVuelto = new javax.swing.JLabel();
        jcbPago = new javax.swing.JComboBox();
        jbtnSprite = new javax.swing.JButton();
        jlblShow = new javax.swing.JLabel();
        jbtnRedbull = new javax.swing.JButton();
        jbtnMonster = new javax.swing.JButton();
        jbtnCorona = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1000");

        jLabel2.setText("1000");

        jLabel3.setText("1000");

        jLabel4.setText("2000");

        jLabel5.setText("2000");

        jLabel6.setText("2000");

        jtxbMonto.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jtxbMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtnpepsi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnpepsi.setText("Pepsi");
        jbtnpepsi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnpepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpepsiActionPerformed(evt);
            }
        });

        jbtnCocaCola.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnCocaCola.setText("CocaCola");
        jbtnCocaCola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnCocaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCocaColaActionPerformed(evt);
            }
        });

        jbtnPago.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jbtnPago.setText("Pagar");
        jbtnPago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPagoActionPerformed(evt);
            }
        });

        jlblVuelto.setText("Tu vuelto es...");

        jcbPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1000", "2000", "5000", " ", " " }));

        jbtnSprite.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnSprite.setText("Sprite");
        jbtnSprite.setToolTipText("");
        jbtnSprite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpriteActionPerformed(evt);
            }
        });

        jlblShow.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jlblShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblShow.setText("Vacio");

        jbtnRedbull.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnRedbull.setText("Redbull");
        jbtnRedbull.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnRedbull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRedbullActionPerformed(evt);
            }
        });

        jbtnMonster.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnMonster.setText("Monster ");
        jbtnMonster.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMonsterActionPerformed(evt);
            }
        });

        jbtnCorona.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnCorona.setText("Corona");
        jbtnCorona.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnCorona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoronaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jcbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jlblVuelto))
                            .addComponent(jtxbVuelto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jlblShow, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jtxbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnpepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnRedbull))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnMonster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnCocaCola))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnCorona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jtxbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnpepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCocaCola)
                    .addComponent(jbtnSprite))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRedbull)
                    .addComponent(jbtnMonster)
                    .addComponent(jbtnCorona))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlblVuelto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxbVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addComponent(jlblShow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnpepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpepsiActionPerformed
       jtxbMonto.setText("1000");
       jlblShow.setVisible(false);
        jlblShow.setText("Pepsi");
 
    }//GEN-LAST:event_jbtnpepsiActionPerformed

    private void jbtnCocaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCocaColaActionPerformed
        jtxbMonto.setText("1000");   
        jlblShow.setVisible(false);
        jlblShow.setText("CocaCola");
        
    }//GEN-LAST:event_jbtnCocaColaActionPerformed

    private void jbtnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagoActionPerformed
          
           int Bebida= parseInt(jtxbMonto.getText());
           String Pagaconstring = (String)jcbPago.getSelectedItem();
           int PagaconInt = Integer.parseInt(Pagaconstring);
            int vuelto= PagaconInt-Bebida;
          //If Que retorna el vuelto   
           if( Bebida <= PagaconInt) {
           jlblVuelto.setVisible(true);
           jtxbVuelto.setText(Integer.toString(vuelto));
           jlblShow.setVisible(true);
    } else{
           JOptionPane.showMessageDialog(null, "Ingresa mas billetes!!");
           }
           
         
        
    }//GEN-LAST:event_jbtnPagoActionPerformed

    private void jbtnSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpriteActionPerformed
        jtxbMonto.setText("1000");       
        jlblShow.setVisible(false);
        jlblShow.setText("Sprite");
        
    }//GEN-LAST:event_jbtnSpriteActionPerformed

    private void jbtnRedbullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRedbullActionPerformed
        jtxbMonto.setText("2000");       
        jlblShow.setVisible(false);
        jlblShow.setText("Redbull");
    }//GEN-LAST:event_jbtnRedbullActionPerformed

    private void jbtnMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMonsterActionPerformed
       jtxbMonto.setText("2000");       
        jlblShow.setVisible(false);
        jlblShow.setText("Monster");
    }//GEN-LAST:event_jbtnMonsterActionPerformed

    private void jbtnCoronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoronaActionPerformed
        jtxbMonto.setText("2000");       
        jlblShow.setVisible(false);
        jlblShow.setText("Corona");
    }//GEN-LAST:event_jbtnCoronaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Face.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Face.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Face.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Face.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Face().setVisible(true);
              }
        });
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton jbtnCocaCola;
    private javax.swing.JButton jbtnCorona;
    private javax.swing.JButton jbtnMonster;
    private javax.swing.JButton jbtnPago;
    private javax.swing.JButton jbtnRedbull;
    private static javax.swing.JButton jbtnSprite;
    private javax.swing.JButton jbtnpepsi;
    private static javax.swing.JComboBox jcbPago;
    private static javax.swing.JLabel jlblShow;
    private static javax.swing.JLabel jlblVuelto;
    private static javax.swing.JTextField jtxbMonto;
    private static javax.swing.JTextField jtxbVuelto;
    // End of variables declaration//GEN-END:variables
}
